-- MySQL Script generated by MySQL Workbench
-- Mon Apr  3 12:42:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema formula_one
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `formula_one` ;

-- -----------------------------------------------------
-- Schema formula_one
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `formula_one` DEFAULT CHARACTER SET utf8 ;
USE `formula_one` ;

-- -----------------------------------------------------
-- Table `formula_one`.`league`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `formula_one`.`league` ;

CREATE TABLE IF NOT EXISTS `formula_one`.`league` (
  `idleague` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idleague`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formula_one`.`team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `formula_one`.`team` ;

CREATE TABLE IF NOT EXISTS `formula_one`.`team` (
  `idteam` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `team_points` INT NULL,
  `league` INT NOT NULL,
  PRIMARY KEY (`idteam`),
  INDEX `fk_team_league_idx` (`league` ASC) VISIBLE,
  CONSTRAINT `fk_team_league`
    FOREIGN KEY (`league`)
    REFERENCES `formula_one`.`league` (`idleague`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `formula_one`.`driver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `formula_one`.`driver` ;

CREATE TABLE IF NOT EXISTS `formula_one`.`driver` (
  `iddriver` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `driver_points` INT NULL,
  `team` INT NOT NULL,
  PRIMARY KEY (`iddriver`),
  INDEX `fk_driver_team1_idx` (`team` ASC) VISIBLE,
  CONSTRAINT `fk_driver_team1`
    FOREIGN KEY (`team`)
    REFERENCES `formula_one`.`team` (`idteam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
